In [1]:
# pip install numpy
import numpy as np

In [2]:
arreglo_np_lista = np.array( [1,2,3] )
arreglo_np_tupla = np.array( (1,2,3) )
print(type(arreglo_np_lista))
print(type(arreglo_np_tupla))
print(arreglo_np_lista)
print(arreglo_np_tupla)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 2 3]
[1 2 3]


In [4]:
np.ones(10000000)

array([1., 1., 1., ..., 1., 1., 1.])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones( (2,3,4 ) )

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [8]:
np.ones( [2,3] )

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.ones( [2,3] ).shape

(2, 3)

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(-20, -10) # [-2, 5[

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [26]:
np.arange(-20, -10, 5)  # [-20, -10[ saltos 5

array([-20, -15])

In [27]:
np.arange(-20, -10, 2)  # [-20, -10[ saltos 2

array([-20, -18, -16, -14, -12])

In [28]:
np.arange(3, 5, 0.1)  # [3, 7[ saltos 2

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [35]:
np.arange(3, 5, 0.1).reshape((5,2,2)).flatten()

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [39]:
np.random.randint(0, 10, size=5)

array([4, 9, 5, 8, 9])

In [40]:
np.random.rand(6)

array([0.69082879, 0.34120225, 0.32500712, 0.64371367, 0.02455605,
       0.22448902])

In [45]:
np.random.randint(0, 10, size = 9).reshape((3,3))

array([[5, 9, 8],
       [9, 2, 6],
       [1, 7, 2]])

In [47]:
a = np.array( [
    [1,2],
    [3,4]])
b = np.array( [
    [5,6],
    [7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [49]:
# Suma
total = a + b
print(a)
print(b)
print(total)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [50]:
# Resta
total = a - b
print(a)
print(b)
print(total)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[-4 -4]
 [-4 -4]]


In [51]:
# Multiplicacion
total = a * b
print(a)
print(b)
print(total)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]


In [52]:
# Division
total = a / b
print(a)
print(b)
print(total)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [58]:
total = a **9
print(total)

[[     1    512]
 [ 19683 262144]]


In [59]:
total = a % 2
print(total)

[[1 0]
 [1 0]]


In [60]:
total = a + 15
print(total)

[[16 17]
 [18 19]]


In [62]:
total = (a * 2) / 5 * 100
print(total)

[[ 40.  80.]
 [120. 160.]]
